# Generated by Django 5.1.3 on 2024-11-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TokenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=255)),
                ('token_type', models.CharField(max_length=50)),
                ('expires_in', models.IntegerField()),
                ('context_id', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('logo_id', models.CharField(max_length=255)),
                ('rx', models.CharField(max_length=255)),
                ('change_setting', models.CharField(max_length=255)),
                ('change_status', models.CharField(max_length=255)),
                ('issued', models.CharField(max_length=255)),
                ('expires', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('batch_id', models.IntegerField()),
                ('login_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('admission_number', models.CharField(max_length=255)),
                ('roll_number', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('admission_date', models.DateField()),
                ('dob', models.DateField()),
                ('profile_picture_id', models.IntegerField()),
                ('aadhaar_number', models.CharField(max_length=12)),
                ('sms_mobile_number', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
