# Generated by Django 5.1.3 on 2024-11-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_usercred'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenmodel',
            name='access_token',
            field=models.CharField(max_length=1000),
        ),
    ]
